homebar/urls.py
from django.urls import path, include
from . import views
from . import url_handler

urlpatterns = [
    path("home", views.HomepageView.as_view(), name="home"),
    path("spirit/<int:pk>/", views.SpiritDetailView.as_view(), name="spirit_detail"),
    path("cocktail/<int:pk>/", views.CocktailDetailView.as_view(), name="cocktail_detail"),
    path("spirit/<int:spirit_id>/comment/create", views.spirit_comment_create, name="spirit_comment_create"),
    path("cocktail/<int:cocktail_id>/comment/create", views.cocktail_comment_create, name="cocktail_comment_create"),
    path("spirit/<int:spirit_id>/comment/<int:comment_id>/delete/", views.spirit_comment_delete, name="spirit_comment_delete"),
    path("cocktail/<int:cocktail_id>/comment/<int:comment_id>/delete/", views.cocktail_comment_delete, name="cocktail_comment_delete"),
    path("spirit/<int:spirit_id>/rating/create", views.spirit_rating_create, name="spirit_rating_create"),
    path("cocktail/<int:cocktail_id>/rating/create", views.cocktail_rating_create, name="cocktail_rating_create"),
    path("spirit/<int:pk>/edit/", views.SpiritEditView.as_view(), name="spirit_edit"),
    path("cocktail/<int:pk>/edit/", views.CocktailEditView.as_view(), name="cocktail_edit"),
    path("spirit/<int:pk>/delete/", views.SpiritDeleteView.as_view(), name="spirit_delete"),
    path("cocktail/<int:pk>/delete/", views.CocktailDeleteView.as_view(), name="cocktail_delete"),
    path("spirit_form/", views.SpiritCreateView.as_view(), name="spirit_form"),
    path("cocktail_form/", views.CocktailCreateView.as_view(), name="cocktail_form"),
    path("spirit_search/", views.spirit_search, name="spirit_search"),
    path("cocktail_search/", views.cocktail_search, name="cocktail_search"),
    path("category/", views.CategoryListView.as_view(), name="category_list"),
    path("cocktail_category/", views.CocktailCategoryListView.as_view(), name="cocktailcategory_list"),
    path("category/<int:category_id>/", views.category_detail, name='category_detail'),
    path("cocktail_category/<int:cocktailcategory_id>/", views.cocktail_category_detail, name='cocktailcategory_detail'),
    path("add_to_collection/<int:spirit_id>/", views.add_to_collection, name="add_to_collection"),
    path("remove_from_collection/<int:spirit_id>/", views.remove_from_collection, name="remove_from_collection"),
    path("remove_from_collection_in_spirit_detail/<int:spirit_id>/", views.remove_from_collection, name="remove_from_collection_in_spirit_detail"),
    path("spirit_collection/", views.view_collection, name="spirit_collection"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path("", url_handler.home_handler),
]

homebar_app/urls.py
from django.contrib import admin
from django.urls import path, include
from homebar import url_handler

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homebar/', include("homebar.urls")),
    path('homebar/', include("django.contrib.auth.urls")),
    path('', url_handler.home_handler),
]

homebar/models.py
from django.contrib.auth.models import User
from django.db import models
from star_ratings.models import Rating as StarRating
import requests
import re
from bs4 import BeautifulSoup

# Create your models here.


class Rating(models.Model):
    star_rating = models.OneToOneField(StarRating, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.star_rating.rating)


class Comment(models.Model):
    text = models.TextField(max_length=300)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text


class Category(models.Model):
    name = models.CharField(max_length=40)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Subcategory(models.Model):
    base_spirit = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    class Meta:
        verbose_name_plural = "Subcategories"

    def __str__(self):
        return self.name


class Spirit(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(
        Subcategory, on_delete=models.CASCADE, null=True
    )
    name = models.CharField(max_length=30)
    price = models.IntegerField(blank=True, null=True)
    url = models.URLField(max_length=200, blank=True, null=True)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.name

    def fetch_price(self):
        if self.url:
            try:
                result = requests.get(self.url)
                doc = BeautifulSoup(result.text, "html.parser")
                tag = doc.find("title")
                price_text = tag.string

                match = re.search(r"\bod\b", price_text)

                if match:
                    start_index = match.end()
                    end_index = price_text.find("Kč", start_index)

                    if end_index >= 0:
                        self.price = price_text[start_index:end_index].strip()
            except Exception:
                pass


class CocktailCategory(models.Model):
    name = models.CharField(max_length=40)

    class Meta:
        verbose_name = "Cocktail Category"
        verbose_name_plural = "Cocktail Categories"

    def __str__(self):
        return self.name


class Cocktail(models.Model):
    name = models.CharField(max_length=25)
    cocktail_category = models.ForeignKey(
        CocktailCategory, on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField("date published")
    base = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    ingredients = models.TextField(max_length=300)
    recipe = models.TextField(max_length=500)

    def __str__(self):
        return self.name


class SpiritComment(models.Model):
    spirit = models.ForeignKey(Spirit, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("spirit", "comment")


class CocktailComment(models.Model):
    cocktail = models.ForeignKey(Cocktail, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("cocktail", "comment")


class SpiritRating(models.Model):
    spirit = models.ForeignKey(Spirit, on_delete=models.CASCADE)
    rating = models.ForeignKey(Rating, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("spirit", "rating")


class CocktailRating(models.Model):
    cocktail = models.ForeignKey(Cocktail, on_delete=models.CASCADE)
    rating = models.ForeignKey(Rating, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("cocktail", "rating")


class UserCollection(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    spirit = models.ForeignKey(Spirit, on_delete=models.CASCADE)
    ratings = models.ManyToManyField(Rating)
    comments = models.ManyToManyField(Comment)

homebar/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views import generic
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
)
from .models import (
    Spirit,
    UserCollection,
    Comment,
    SpiritComment,
    SpiritRating,
    Rating,
    Cocktail,
    CocktailComment,
    Category,
    CocktailRating,
    CocktailCategory,
)
from star_ratings.models import Rating as StarRating
import requests
from bs4 import BeautifulSoup
from .forms import SpiritForm, RegistrationForm, CocktailForm
from .suggestion_logic import suggest_cocktail


# Create your views here.


class SpiritDetailView(generic.DetailView):
    model = Spirit
    template_name = "homebar/spirit_detail.html"
    context_object_name = "spirit"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        spirit = context["spirit"]
        comments = SpiritComment.objects.filter(spirit=spirit)
        category = self.object.category
        subcategory = self.object.subcategory

        if user.is_authenticated:
            user_has_spirit_in_collection = UserCollection.objects.filter(
                user=user, spirit=spirit
            ).exists()
        else:
            user_has_spirit_in_collection = False

        context[
            "user_has_spirit_in_collection"
        ] = user_has_spirit_in_collection
        context["spiritcomment"] = comments
        context["category"] = category
        context["subcategory"] = subcategory
        spirit.fetch_price()
        context["price"] = spirit.price
        return context


class SpiritCreateView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.edit.CreateView
):
    form_class = SpiritForm
    template_name = "homebar/spirit_form.html"
    permission_required = "homebar.add_choice"

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            spirit = form.save(commit=False)
            spirit.pub_date = timezone.now()
            spirit.save()
        return redirect(reverse("category_list"))


class SpiritEditView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.edit.UpdateView
):
    model = Spirit
    fields = ["category", "name"]
    template_name_suffix = "_edit_form"
    permission_required = "homebar.change_choice"

    def get_success_url(self):
        return reverse("spirit_detail", kwargs={"pk": self.object.pk})


class SpiritDeleteView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.edit.DeleteView
):
    model = Spirit
    success_url = reverse_lazy("category_list")
    permission_required = "homebar.delete_choice"


class CocktailDetailView(generic.DetailView):
    model = Cocktail
    template_name = "homebar/cocktail_detail.html"
    context_object_name = "cocktail"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cocktail = context["cocktail"]
        comments = CocktailComment.objects.filter(cocktail=cocktail)

        if self.request.user.is_authenticated:
            user = self.request.user
            spirit_in_user_collection = UserCollection.objects.filter(
                user=user
            ).values_list("spirit__subcategory", flat=True)
        else:
            spirit_in_user_collection = []

        context["cocktail_category"] = self.object.cocktail_category
        context["cocktailcomment"] = comments
        context["spirit_in_user_collection"] = spirit_in_user_collection
        return context


class CocktailCreateView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.edit.CreateView
):
    form_class = CocktailForm
    template_name = "homebar/cocktail_form.html"
    permission_required = "homebar.add_choice"

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cocktail = form.save(commit=False)
            cocktail.pub_date = timezone.now()
            cocktail.save()
        return redirect(reverse("cocktailcategory_list"))


class CocktailEditView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.edit.UpdateView
):
    model = Cocktail
    fields = ["name", "base", "ingredients"]
    template_name_suffix = "_edit_form"
    permission_required = "homebar.change_choice"

    def get_success_url(self):
        return reverse("cocktail_detail", kwargs={"pk": self.object.pk})


class CocktailDeleteView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.edit.DeleteView
):
    model = Cocktail
    success_url = reverse_lazy("cocktailcategory_list")
    permission_required = "homebar.delete_choice"


def spirit_search(request):
    if request.method == "POST":
        searched = request.POST["searched"]
        spirits = Spirit.objects.filter(name__contains=searched)
        return render(
            request,
            "homebar/spirit_search.html",
            {"searched": searched, "spirits": spirits},
        )
    return render(request, "homebar/spirit_search.html", {})


def cocktail_search(request):
    if request.method == "POST":
        searched = request.POST["searched"]
        cocktails = Cocktail.objects.filter(name__contains=searched)
        return render(
            request,
            "homebar/cocktail_search.html",
            {"searched": searched, "cocktails": cocktails},
        )
    return render(request, "homebar/cocktail_search.html", {})


class CategoryListView(generic.ListView):
    queryset = Category.objects.all()
    context_object_name = "category"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        spirit_list = Spirit.objects.order_by("-pub_date")[:5]
        context["spirit_list"] = spirit_list
        return context


def category_detail(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    spirits_in_category = Spirit.objects.filter(category=category)
    return render(
        request,
        "homebar/category_detail.html",
        {"category": category, "spirits_in_category": spirits_in_category},
    )


@login_required(login_url="/login")
def add_to_collection(request, spirit_id):
    if request.method == "GET":
        spirit = Spirit.objects.get(id=spirit_id)
        user = request.user
        if not UserCollection.objects.filter(
            user=user, spirit=spirit
        ).exists():
            UserCollection.objects.create(user=user, spirit=spirit)
        else:
            messages.info(
                request, "You already have this spirit in your collection!"
            )
    spirit_detail_url = reverse("spirit_detail", args=[spirit_id])
    return redirect(spirit_detail_url)


@login_required(login_url="/login")
def remove_from_collection(request, spirit_id):
    if request.method == "POST":
        spirit = Spirit.objects.get(id=spirit_id)
        user = request.user
        try:
            collection_entry = UserCollection.objects.get(
                user=user, spirit=spirit
            )
            collection_entry.delete()
        except UserCollection.DoesNotExist:
            messages.info(
                request, "You don't have this spirit in your collection!"
            )
    spirit_detail_url = reverse("spirit_detail", args=[spirit_id])
    return redirect(spirit_detail_url)


@login_required(login_url="/login")
def remove_from_collection_in_spirit_detail(request, spirit_id):
    if request.method == "POST":
        spirit = Spirit.objects.get(id=spirit_id)
        user = request.user
        try:
            collection_entry = UserCollection.objects.get(
                user=user, spirit=spirit
            )
            collection_entry.delete()
        except UserCollection.DoesNotExist:
            messages.info(
                request, "You don't have this spirit in your collection!"
            )
    collection = UserCollection.objects.filter(user=request.user)
    return render(request, "homebar/spirit_detail.html", {"spirit": spirit})


@login_required(login_url="/login")
def view_collection(request):
    if request.method == "GET":
        collection = UserCollection.objects.filter(user=request.user)
        suggested_cocktail = suggest_cocktail(request.user)
        return render(
            request,
            "homebar/spirit_collection.html",
            {
                "collection": collection,
                "suggested_cocktail": suggested_cocktail,
            },
        )


def sign_up(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("/homebar/home")
    else:
        form = RegistrationForm()
    return render(request, "registration/sign_up.html", {"form": form})


@login_required(login_url="/login")
def spirit_comment_create(request, spirit_id):
    spirit = get_object_or_404(Spirit, id=spirit_id)
    if request.method == "POST":
        commented = request.POST["commented"]
        if commented:
            comment = Comment.objects.create(
                text=commented, author=request.user
            )
            SpiritComment.objects.create(spirit=spirit, comment=comment)

    return redirect("spirit_detail", pk=spirit_id)


@login_required(login_url="/login")
def spirit_comment_delete(request, spirit_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.method == "POST":
        if (
            request.user.is_superuser
            or comment.author.username == request.user.username
        ):
            comment.delete()

    return redirect("spirit_detail", pk=spirit_id)


@login_required(login_url="/login")

homebar/templates/homebar/category_detail.html
{% extends "base.html" %}

{% block content %}
<h2>{{ category.name }}</h2>
<ul>
    {% for spirit in spirits_in_category %}
        <li class="list-group-item"><a href="{% url 'spirit_detail' spirit.id %}">{{ spirit.name }}</a></li>
    {% empty %}
        <li class="list-group-item">No spirits in this category yet.</li>
    {% endfor %}
</ul>
{% endblock %}

homebar/templates/homebar/cocktail_detail.html
{% extends "base.html" %}
{% load ratings %}
{% block content %}
    <h2>Cocktail Details</h2><br>
    <h3>{{ cocktail.name }}</h3><br>
    {% if cocktail.base.name == 'Vodka' %}
    <h4>Base: {{ cocktail.base }}</h4>
    {% else %}
    <h4>Base: {{ cocktail.base }} {{cocktail.base.base_spirit }}</h4>
    {% endif %}
    <h5>Additional Ingredients: {{ cocktail.ingredients }}</h5>
    {% if user.is_superuser %}<h6>Added {{ cocktail.pub_date }}</h6>{% endif %}
    <p>{{ cocktail.recipe }}</p>
 <div class="star-ratings">
        {% ratings cocktail %}
 </div>
{% if user.is_authenticated %}
    {% if cocktail.base_id in spirit_in_user_collection %}
<p><strong>Since you have {{ cocktail.base }} {{ cocktail.base.base_spirit }} in your collection, you can try this cocktail right away!</strong></p>
    {% else %}
        {% if cocktail.base.name == cocktail.base.base_spirit.name %}
            <p><strong>Sadly, you are missing {{ cocktail.base }} in your collection to try this one out!</strong></p>
        {% else %}
            <p><strong>Sadly, you are missing {{ cocktail.base }} {{ cocktail.base.base_spirit }} in your collection to try this one out!</strong></p>
        {% endif %}
    {% endif %}
{% endif %}
    <br><br>
    <button type="button" class="btn btn-secondary btn-sm"><a class="white" href="{% url 'cocktailcategory_detail' cocktail_category.id %}">Back</a></button>
    {% if user.is_superuser %}
    <button type="button" class="btn btn-warning btn-sm"><a class="white" href="{% url 'cocktail_edit' cocktail.id %}">Edit</a></button>
    <button type="button" class="btn btn-danger btn-sm"><a class="white" href="{% url 'cocktail_delete' cocktail.id %}">Delete</a></button>
    {% endif %}
    <h4>{{ cocktail.rating }}</h4><br>
    <h2>Comments</h2>
    {% for comment in cocktailcomment %}
    <div class="card mt-2">
        <div class="card-header"><strong>{{ comment.comment.author.username }}&ensp;{{ comment.comment.created_at }}</strong></div>
        <div class="card-body d-flex flex-row justify-content-between">
             <div>
                 <p>{{ comment.comment.text }}</p>
             </div>
             <div>
                 {% if user.is_superuser or comment.comment.author.username == request.user.username %}
                 <form method="POST" action="{% url 'cocktail_comment_delete' cocktail.id comment.id %}">
                     {% csrf_token %}
                     <button type="submit" class="btn btn-danger">Delete Comment</button>
                 </form>
                 {% endif %}
             </div>
        </div>
    </div><br>
    {% empty %}
    <p>No comments yet.</p>
    {% endfor %}
    {% if user.is_authenticated %}
    <form method="POST" action="{% url 'cocktail_comment_create' cocktail.id %}">
        {% csrf_token %}
        <input placeholder="Leave a comment..." name="commented">
        <button class="btn btn-primary" type="submit">Comment</button>
    </form>
    {% endif %}
{% endblock %}

homebar/templates/homebar/cocktail_edit_form.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<br><h2>Edit Cocktail</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
    <input type="submit">
</form><br>
<button><a href="{% url 'cocktailcategory_list' %}">Back</a></button>
{% endblock %}

homebar/templates/homebar/cocktail_form.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<br><h2>Create New Cocktail</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
    <input type="submit">
</form><br>
<button class="btn btn-secondary btn-sm"><a class="white" href="{% url 'cocktailcategory_list' %}">Back</a></button>
{% endblock %}

homebar/templates/homebar/cocktail_search.html
{% extends "base.html" %}
{% block content %}
    {% if searched %}
        <h2>You Searched For {{ searched }}</h2>
        <br>
        {% for cocktail in cocktails %}
            <a href="{% url 'cocktail_detail' cocktail.id %}">{{ cocktail }}</a><br>
        {% endfor %}
    {% else %}
        <h2>You haven't specify what you're searching for!</h2>
    {% endif %}
<button><a href="{% url 'cocktailcategory_list' %}">Back</a></button>
{% endblock %}

homebar/templates/homebar/cocktailcategory_detail.html
{% extends "base.html" %}

{% block content %}
<h2>{{ cocktail_category.name }}</h2>
<ul>
    {% for cocktail in cocktails_in_category %}
        <li class="list-group-item"><a href="{% url 'cocktail_detail' cocktail.id %}">{{ cocktail.name }}</a></li>
    {% empty %}
        <li class="list-group-item">No cocktails in this category yet.</li>
    {% endfor %}
</ul>
{% endblock %}

homebar/templates/homebar/cocktailcategory_list.html
{% extends "base.html" %}
{% block content %}
    <h1>Cocktail Categories</h1>
    <ul class="light-group">
        {% for cocktailcategory in cocktailcategory %}
            <li class="list-group-item"><a href="{% url 'cocktailcategory_detail' cocktailcategory.id %}">{{ cocktailcategory.name }}</a></li>
        {% endfor %}
    </ul>
{% if user.is_superuser %}
<button class="btn btn-primary"><a class="white" href="{% url 'cocktail_form' %}">Create New Cocktail</a></button>
{% endif %}
<form method="POST" action="{% url 'cocktail_search' %}">
  {% csrf_token %}
  <input type="search" placeholder="Search for a cocktail..." name="searched">
  <button class="btn btn-secondary" type="submit">Search</button>
</form>
  <br><br><h2>Recently Added Cocktails</h2>
  <ul class="light-group">
    {% for cocktail in cocktail_list %}
        <li class="list-group-item"><a href="{% url 'cocktail_detail' cocktail.id %}">{{ cocktail.name }}</a></li>
    {% empty %}
      <li>No cocktails entered yet!</li>
    {% endfor %}
  </ul>
{% endblock %}

homebar/templates/homebar/spirit_collection.html
{% extends "base.html" %}
{% block content %}
    <h1>Your Spirit Collection</h1>
    <ul>
        {% for item in collection %}
            <li>
                {{ item.spirit.name }}
                <form method="post" action="{% url 'remove_from_collection' item.spirit.id %}">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit">Remove from collection</button>
                </form>
            </li>
    </ul>
        {% empty %}
        <p>You have no spirits in your collection yet.</p>
        {% endfor %}
<h2>Cocktail suggestions</h2>
    {% if suggested_cocktail %}
        <p>Since you have {{ suggested_cocktail.base }} {{ suggested_cocktail.base.base_spirit }} in your collection, we suggest you try: {{ suggested_cocktail.name }}</p>
        <p>Ingredients: {{ suggested_cocktail.base }}, {{ suggested_cocktail.ingredients }}</p>
    {% else %}
        <p>No suggested cocktails at the moment.</p>
    {% endif %}
{% endblock %}

homebar/templates/homebar/spirit_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form|crispy }}
        <input type="submit" value="Confirm">
</form>
<button><a href="{% url 'category_list' %}">Back</a></button>
{% endblock %}

homebar/templates/homebar/spirit_detail.html
{% extends "base.html" %}
{% load ratings %}
{% block content %}
    <h2>Spirit Details</h2><br>
    <h3>{{ spirit.name }}</h3><br>
    <h4>{% if spirit.category.name == spirit.subcategory.name %}
            {{ spirit.category }}
        {% else %}
            {{ spirit.subcategory }} {{ spirit.category }}
        {% endif %}</h4><br>
    {% if user.is_superuser %}<h6>Added {{ spirit.pub_date }}</h6>{% endif %}
    <div class="star-ratings">
        {% ratings spirit %}
    </div><br><br>
    {% if user.is_authenticated %}
        {% if not user_has_spirit_in_collection %}
            {% if spirit.url %}
                <p><a href="{{ spirit.url }}" target="_blank">Buy it on Heureka. Price starting at {{ spirit.price }} Kč.</a></p>
            {% else %}
                <p>Price starting at {{ spirit.price }} Kč.</p>
            {% endif %}
        <button type="button" class="btn btn-primary btn-lg active" role="button" aria-pressed="true"><a class="white" href="{% url 'add_to_collection' spirit.id %}">Add to Collection</a></button>
    {% else %}
        <p>You have this in your collection.</p>
        <form method="post" action="{% url 'remove_from_collection_in_spirit_detail' spirit.id %}">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Remove from collection</button>
        </form>
        {% endif %}
    {% endif %}
    <br><br>
    <button type="button" class="btn btn-secondary btn-sm"><a class="white" href="{% url 'category_detail' category.id %}">Back</a></button>
    {% if user.is_superuser %}
    <button type="button" class="btn btn-warning btn-sm"><a class="white" href="{% url 'spirit_edit' spirit.id %}">Edit</a></button>
    <button type="button" class="btn btn-danger btn-sm"><a class="white" href="{% url 'spirit_delete' spirit.id %}">Delete</a></button>
    {% endif %}
    <h4>{{ spirit.rating }}</h4><br>
    <h2>Comments</h2>
    {% for comment in spiritcomment %}
    <div class="card mt-2">
        <div class="card-header"><strong>{{ comment.comment.author.username }}&ensp;{{ comment.comment.created_at }}</strong></div>
        <div class="card-body d-flex flex-row justify-content-between">
             <div>
                 <p>{{ comment.comment.text }}</p>
             </div>
             <div>
                 {% if user.is_superuser or comment.comment.author.username == request.user.username %}
                 <form method="POST" action="{% url 'spirit_comment_delete' spirit.id comment.id %}">
                     {% csrf_token %}
                     <button type="submit" class="btn btn-danger">Delete Comment</button>
                 </form>
                 {% endif %}
             </div>
        </div>
    </div><br>
    {% empty %}
    <p>No comments yet.</p>
    {% endfor %}
    {% if user.is_authenticated %}
    <form method="POST" action="{% url 'spirit_comment_create' spirit.id %}">
        {% csrf_token %}
        <input placeholder="Leave a comment..." name="commented">
        <button class="btn btn-primary" type="submit">Comment</button>
    </form>
    {% endif %}
{% endblock %}

homebar/templates/homebar/spirit_edit_form.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<br><h2>Edit Spirit</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
    <input type="submit">
</form><br>
<button><a href="{% url 'category_list' %}">Back</a></button>
{% endblock %}

homebar/templates/homebar/spirit_form.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<br><h2>Create New Spirit</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
    <input type="submit">
</form><br>
<button class="btn btn-secondary btn-sm"><a class="white" href="{% url 'category_list' %}">Back</a></button>
{% endblock %}

homebar/templates/homebar/spirit_price.html
{% extends "base.html" %}
{% block content %}
    <h2>Spirit Price Details</h2>
    <h3>{{ spirit.name }}</h3>
    <p>Price: ${{ price }}</p>
    <p><a href="{{ spirit.url }}" target="_blank">Buy it here</a></p>
{% endblock %}

homebar/templates/homebar/spirit_search.html
{% extends "base.html" %}
{% block content %}
    {% if searched %}
        <h2>You Searched For {{ searched }}</h2>
        <br>
        {% for spirit in spirits %}
            <a href="{% url 'spirit_detail' spirit.id %}">{{ spirit }}</a><br>
        {% endfor %}
    {% else %}
        <h2>You haven't specify what you're searching for!</h2>
    {% endif %}
<button><a href="{% url 'category_list' %}">Back</a></button>
{% endblock %}